# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for iOSProject
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'Masonry', '~> 1.1.0'
  pod 'SDWebImage', '~> 5.0.4'
  pod 'MJExtension', '~> 3.0.15.1'
  pod 'MJRefresh', '3.1.15.7'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
  # 轮播图
  pod 'SDCycleScrollView', '~> 1.80'
  # 占位
  pod 'LYEmptyView', '~> 1.2.3'
  # 友盟 基础库
  
  pod 'PGDatePicker'
  
  pod 'Charts', '~> 3.1.1'
  
  
end
